name: production build

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: npm ci
      - name: create production build
        run: npm run build
      - name: run tests
        run: npm test
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: print directiory
        run: ls -las
      - name: Push to s3
        run: |
          aws s3 sync build/ s3://covid-19-us-tracker
          aws s3 cp build/index.html s3://covid-19-us-tracker --cache-control no-cache
